on:
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: axel-op/containerized-dart-action@master
        id: dart-action
        with:
          who-to-greet: "LEQLELQLE"
      - run: echo 'The time was ${{ steps.dart-action.outputs.time }}'
